ChatroomModel
Tendencias-Grupo-2/simple-chat-application pull request #44
Opened 2021-01-06 23:50 UTC by LightspeedDude

2021-01-06 23:54 UTC, LightspeedDude commented
Added ChatroomModel

2021-01-06 23:58 UTC, rem1niscence requested changes
Also, as a another rule of thumb. Commit messages should always be written in imperative form (in order words: in present tense)

2021-01-06 23:58 UTC, rem1niscence commented on simple-chat-back/src/models/chatroomModel.js
> +const mongoose = require('mongoose');
remove semicolon, @Lunaticfrg0  configured the project to not use them

2021-01-06 23:58 UTC, rem1niscence commented on simple-chat-back/src/models/chatroomModel.js
> +module.exports = Chatroom
add an empty newline. As a rule of thumb, all files should always end with an empty newline

2021-01-06 23:58 UTC, rem1niscence commented on simple-chat-back/src/models/chatroomModel.js
> +const Chatroom = mongoose.model('Chatroom', chatroomSchema )
remove space before closing parentheses

2021-01-07 01:29 UTC, rem1niscence approved these changes

2021-01-07 01:30 UTC, merged